
#line 3 "<stdout>"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 158
#define YY_END_OF_BUFFER 159
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[537] =
    {   0,
        0,    0,  159,  157,    2,    1,   35,  155,  157,   26,
       29,  151,   13,   14,   24,   22,   66,   23,   20,   25,
      146,  146,   16,   15,   38,   37,   39,   18,  143,  143,
        9,   11,   27,  143,  143,  143,  143,  143,  143,  143,
      143,  143,  143,  143,  143,  143,  143,  143,  143,  143,
      143,  143,  143,    5,   31,    7,   33,    2,   56,  155,
      153,  155,    0,   44,    8,   60,   47,  151,  149,  151,
       42,   64,   40,   65,   41,   68,   21,    0,  147,    3,
        4,   43,  147,  145,  146,    0,  146,  146,    0,   19,
       12,    6,   10,   51,   58,   55,   59,   52,  143,  156,

      152,   45,  143,  143,  143,  143,  143,  143,  143,  143,
      143,  143,  143,   83,  143,  143,  143,  143,  143,  143,
      143,  143,  143,   96,  143,  143,  143,  143,  143,  143,
      143,   63,  143,  143,  143,  143,  143,  143,  143,  143,
      143,  143,  143,  143,  143,  143,  143,  143,  143,  143,
       49,   62,  155,  153,  155,    0,  151,  149,  151,   67,
       17,    0,  147,  145,  145,    0,  148,  146,  146,  144,
       53,   54,  156,  154,  156,  152,  150,  152,   61,   70,
      143,  143,  143,  143,  143,  143,  143,  143,  143,  143,
      143,  143,  143,  143,  143,  143,  143,  143,  143,  143,

       93,  143,  143,  143,   98,  143,  143,  143,  102,   36,
      143,  143,  143,  143,  143,  143,  143,  143,  143,  143,
      143,  143,  143,  143,  143,  143,  143,  143,  121,  143,
      143,  143,  143,  143,  143,  143,  143,  143,   28,    0,
        0,  147,  145,  145,  148,  144,  144,  156,  154,  156,
      152,  150,  152,  143,   71,  143,  143,   72,  143,   74,
      143,   76,  143,  143,  143,  143,  143,  143,  143,  143,
       86,   87,  143,  143,  143,  143,  143,  143,   95,  143,
       99,  143,  143,  143,  143,  143,  143,  143,  143,  143,
      143,  143,  143,  143,  143,  143,  143,  143,  143,  118,

      143,  120,  143,  143,  143,  143,  143,  129,  143,  143,
      143,  143,    0,  144,  144,  143,  143,   32,   73,   75,
       77,   34,   78,  143,  143,  143,  143,  143,  143,  143,
      143,   91,   92,  143,  143,  143,  143,  143,  143,   50,
      143,  143,  143,  143,  143,  143,  110,  143,  143,  143,
      143,  143,  143,  119,  143,  143,  143,  125,  143,  127,
      143,  143,  143,  132,  143,    0,   48,   30,  143,  143,
      143,   82,   84,  143,  143,   89,   90,   94,   97,  143,
      143,   57,  143,  143,  143,  106,  143,  143,  109,  111,
      112,  113,  115,  116,  143,  143,  123,  143,  143,    0,

      143,  143,  143,   46,    0,  143,  143,   81,  143,  143,
      100,  143,  143,  104,  143,  143,  143,  143,  143,  122,
      143,  143,    0,  128,  143,  131,    0,  143,   80,  143,
       88,  143,  103,  143,  107,  143,  143,  117,  124,  126,
        0,  130,    0,    0,    0,  143,  143,  101,  105,  143,
      143,    0,    0,    0,    0,    0,    0,   79,  143,  143,
      143,    0,  133,    0,    0,    0,    0,    0,    0,  143,
      143,  114,    0,    0,    0,    0,    0,    0,    0,    0,
       85,  143,    0,    0,    0,    0,    0,    0,    0,    0,
        0,  143,    0,    0,    0,    0,    0,    0,    0,    0,

        0,  143,    0,  142,    0,  136,    0,    0,    0,    0,
        0,  143,    0,    0,    0,    0,    0,    0,    0,  137,
      108,    0,  135,  139,    0,  140,    0,    0,    0,  134,
      141,  138,    0,    0,   69,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    1,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   20,
       20,   20,   20,   20,   20,   21,   21,   22,   23,   24,
       25,   26,   27,    1,   28,   28,   28,   28,   29,   30,
       31,   31,   31,   31,   31,   32,   31,   31,   31,   31,
       31,   31,   31,   31,   33,   31,   31,   34,   31,   31,
       35,   36,   37,   38,   39,    1,   40,   41,   42,   43,

       44,   45,   46,   47,   48,   31,   49,   50,   51,   52,
       53,   54,   55,   56,   57,   58,   59,   60,   61,   62,
       63,   64,   65,   66,   67,   68,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[69] =
    {   0,
        1,    1,    1,    1,    1,    2,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    3,    3,
        3,    1,    1,    1,    1,    1,    1,    3,    3,    3,
        4,    4,    4,    4,    1,    2,    1,    1,    4,    3,
        3,    3,    3,    3,    3,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    1,    1,    1,    1
    } ;

static yyconst flex_int16_t yy_base[548] =
    {   0,
        0,    0,  704,  705,   67,  705,  678,   64,  654,   47,
       65,   65,  705,  705,  676,   62,  705,   63,   64,   73,
       85,   92,   56,  705,   72,  675,   67,  705,    0,   89,
      705,  705,  674,   51,   67,   87,   63,   81,   99,  645,
       93,  644,  637,   88,   92,   94,  651,  109,  115,  106,
      112,  119,  641,  705,  129,  705,  705,  170,  705,  158,
      705,  170,  641,  705,  705,  705,  705,  165,  705,  174,
      705,  705,  705,  705,  705,  679,  705,  674,  167,  705,
      705,  705,  184,  203,  222,  244,  148,  148,    0,  705,
      705,  705,  705,  665,  705,  705,  705,  664,    0,  173,

      172,  705,  645,  636,  628,  627,  631,  639,  111,  642,
      641,  138,  176,  621,  627,  621,  618,  161,  626,  622,
      618,  625,  614,    0,   72,  619,  612,  618,  607,  609,
      622,  626,  177,  623,  192,  610,  154,  193,  614,  610,
      135,  168,  606,  145,  611,  602,  196,  610,  608,  599,
      705,  705,  231,  239,  253,  612,  238,  242,  258,  705,
      705,  263,  705,  236,  238,  266,  271,  705,  705,  264,
      705,  705,  270,  705,  296,  283,  705,  295,  614,    0,
      599,  260,  601,  610,  605,  606,  591,  589,  591,  250,
      604,  599,  601,  601,  596,  588,  259,  594,  580,  596,

        0,  591,  581,  585,    0,  586,  591,  586,    0,  590,
      572,  583,  566,  567,  574,  575,  570,  562,  564,  567,
      574,  559,  557,  557,  560,  556,  559,  567,    0,  566,
      556,  560,  555,  548,  562,  564,  563,  552,  562,  550,
      305,  308,  705,  705,  705,  271,  283,  274,  305,  314,
      308,  312,  332,  555,    0,  546,  541,    0,  547,    0,
      548,    0,  537,  543,  534,  543,  531,  531,  538,  536,
        0,    0,  538,  529,  528,  539,  524,  529,    0,  528,
        0,  538,  521,  533,  536,  520,  534,  529,  524,  514,
      512,  513,  510,  523,  513,  517,  522,  521,  512,    0,

      500,    0,  291,  508,  513,  512,  498,    0,  498,  499,
      510,  509,  493,  705,  705,  496,  507,    0,    0,    0,
        0,    0,  510,  496,  497,  502,  501,  496,  501,  484,
      489,    0,    0,  497,  495,  488,  483,  481,  477,    0,
      476,  491,  490,  473,  486,  477,    0,  485,  482,  484,
      467,  477,  483,    0,  478,  478,  480,    0,  467,  514,
      477,  468,  476,    0,  459,  470,    0,    0,  470,  452,
      452,    0,    0,  467,  460,    0,    0,    0,    0,  463,
      466,    0,  452,  460,  445,    0,  458,  445,    0,    0,
        0,  461,    0,    0,  441,  453,    0,  446,  452,  443,

      444,  443,  434,    0,  447,  450,  445,    0,  449,  429,
        0,  444,  429,    0,  440,  427,  428,  439,  436,    0,
      435,  435,  437,    0,  432,    0,  341,  418,    0,  432,
        0,  429,    0,  429,    0,  415,  430,    0,    0,    0,
      418,    0,  345,    0,  314,  410,  427,    0,    0,  422,
      408,  420,  457,  303,  405,  408,  402,    0,  402,  400,
      399,  399,  705,  415,  396,  405,  394,  394,  314,  392,
      410,    0,  394,  389,  403,  394,  388,  385,  223,  394,
        0,  399,  400,  392,  388,  393,  392,  379,  381,  385,
      380,  391,  388,  403,  380,  401,  386,  381,  407,  382,

      376,  364,  376,  705,  378,  705,  367,  377,  369,  398,
      320,  356,  409,  386,  385,  359,  381,  320,  319,  705,
        0,  307,  705,  705,  337,  705,  329,  326,  278,  705,
      705,  705,  214,  169,  705,  705,  371,  375,  377,  381,
      385,  182,  389,  393,  397,  401,  405
    } ;

static yyconst flex_int16_t yy_def[548] =
    {   0,
      536,    1,  536,  536,  536,  536,  536,  537,  536,  536,
      536,  538,  536,  536,  536,  536,  536,  536,  536,  536,
      536,  536,  536,  536,  536,  536,  536,  536,  539,  539,
      536,  536,  536,  539,  539,  539,  539,  539,  539,  539,
      539,  539,  539,  539,  539,  539,  539,  539,  539,  539,
      539,  539,  539,  536,  536,  536,  536,  536,  536,  537,
      536,  540,  536,  536,  536,  536,  536,  538,  536,  541,
      536,  536,  536,  536,  536,  536,  536,  536,  536,  536,
      536,  536,  536,  536,  536,  536,  536,  536,  542,  536,
      536,  536,  536,  536,  536,  536,  536,  536,  539,  543,

      544,  536,  539,  539,  539,  539,  539,  539,  539,  539,
      539,  539,  539,  539,  539,  539,  539,  539,  539,  539,
      539,  539,  539,  539,  539,  539,  539,  539,  539,  539,
      539,  539,  539,  539,  539,  539,  539,  539,  539,  539,
      539,  539,  539,  539,  539,  539,  539,  539,  539,  539,
      536,  536,  537,  537,  540,  536,  538,  538,  541,  536,
      536,  536,  536,  536,  536,  536,  536,  536,  536,  542,
      536,  536,  543,  536,  545,  544,  536,  546,  539,  539,
      539,  539,  539,  539,  539,  539,  539,  539,  539,  539,
      539,  539,  539,  539,  539,  539,  539,  539,  539,  539,

      539,  539,  539,  539,  539,  539,  539,  539,  539,  539,
      539,  539,  539,  539,  539,  539,  539,  539,  539,  539,
      539,  539,  539,  539,  539,  539,  539,  539,  539,  539,
      539,  539,  539,  539,  539,  539,  539,  539,  539,  536,
      536,  536,  536,  536,  536,  536,  536,  543,  543,  545,
      544,  544,  546,  539,  539,  539,  539,  539,  539,  539,
      539,  539,  539,  539,  539,  539,  539,  539,  539,  539,
      539,  539,  539,  539,  539,  539,  539,  539,  539,  539,
      539,  539,  539,  539,  539,  539,  539,  539,  539,  539,
      539,  539,  539,  539,  539,  539,  539,  539,  539,  539,

      539,  539,  539,  539,  539,  539,  539,  539,  539,  539,
      539,  539,  536,  536,  536,  539,  539,  539,  539,  539,
      539,  539,  539,  539,  539,  539,  539,  539,  539,  539,
      539,  539,  539,  539,  539,  539,  539,  539,  539,  539,
      539,  539,  539,  539,  539,  539,  539,  539,  539,  539,
      539,  539,  539,  539,  539,  539,  539,  539,  539,  539,
      539,  539,  539,  539,  539,  536,  539,  539,  539,  539,
      539,  539,  539,  539,  539,  539,  539,  539,  539,  539,
      539,  539,  539,  539,  539,  539,  539,  539,  539,  539,
      539,  539,  539,  539,  539,  539,  539,  539,  539,  536,

      539,  539,  539,  539,  536,  539,  539,  539,  539,  539,
      539,  539,  539,  539,  539,  539,  539,  539,  539,  539,
      539,  539,  536,  539,  539,  539,  536,  539,  539,  539,
      539,  539,  539,  539,  539,  539,  539,  539,  539,  539,
      536,  539,  536,  547,  536,  539,  539,  539,  539,  539,
      539,  536,  547,  536,  536,  536,  536,  539,  539,  539,
      539,  536,  536,  536,  536,  536,  536,  536,  536,  539,
      539,  539,  536,  536,  536,  536,  536,  536,  536,  536,
      539,  539,  536,  536,  536,  536,  536,  536,  536,  536,
      536,  539,  536,  536,  536,  536,  536,  536,  536,  536,

      536,  539,  536,  536,  536,  536,  536,  536,  536,  536,
      536,  539,  536,  536,  536,  536,  536,  536,  536,  536,
      539,  536,  536,  536,  536,  536,  536,  536,  536,  536,
      536,  536,  536,  536,  536,    0,  536,  536,  536,  536,
      536,  536,  536,  536,  536,  536,  536
    } ;

static yyconst flex_int16_t yy_nxt[774] =
    {   0,
        4,    5,    6,    5,    7,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
       22,   23,   24,   25,   26,   27,   28,   29,   29,   29,
       29,   30,   29,   29,   31,    4,   32,   33,   29,   34,
       35,   36,   37,   38,   39,   40,   29,   41,   29,   42,
       43,   44,   45,   46,   29,   47,   48,   49,   50,   51,
       52,   53,   29,   29,   54,   55,   56,   57,   58,   61,
       58,   64,   65,   66,   69,   72,   77,   90,   74,   92,
       78,   91,   79,   79,   79,   80,   73,   75,   76,   67,
       81,   97,   98,   93,  100,   94,   95,   82,  101,   62,

       70,   83,  103,   84,   84,   85,  113,  104,   83,  105,
       85,   85,   85,   86,  106,  114,   87,   88,   89,  107,
       86,  204,  108,   87,   88,  115,  109,  128,   86,  205,
      116,  129,  117,  110,   87,   86,  111,  124,  119,  112,
      130,   87,  118,   88,  125,  131,   89,  132,  120,  133,
       88,  121,  134,  151,  122,  136,  137,  144,  140,  146,
      148,  141,  145,   61,  147,  149,  138,  185,  186,  139,
      142,   58,   60,   58,   69,  154,   68,  143,  174,  169,
      168,  177,  226,  158,  170,   79,   79,   79,  189,  190,
      227,  535,  231,   62,  152,  162,  163,  169,  163,  220,

       70,  232,   79,   79,   79,  155,  168,  178,  175,  159,
      162,  163,  162,  163,  197,  163,  163,  221,  198,   83,
      191,   84,   84,   85,  213,  192,  228,  162,  163,  214,
      229,   86,  222,  163,  164,  165,   61,  216,   83,  217,
       85,   85,   85,  235,   61,  236,   86,   69,  223,  218,
       86,   69,  164,   87,   88,   60,  534,  166,  154,  166,
       68,  165,  167,  167,  167,   86,   62,  158,  243,  244,
      489,   87,  490,   70,   62,  174,  241,   70,  241,  174,
       88,  242,  242,  242,  167,  167,  167,  244,  155,  167,
      167,  167,  177,  159,  243,  246,  247,  176,  173,  256,

      245,  249,  245,  314,  252,  175,  265,  266,  273,  175,
      174,  274,  257,  246,  315,  245,  173,  177,  178,  249,
      245,  177,  247,  242,  242,  242,  242,  242,  242,  314,
      253,  250,  315,  355,  176,  533,  519,  163,  356,  163,
      175,  252,  357,  178,  443,  520,  444,  178,  443,  250,
      444,  532,  163,  464,  531,  454,  479,  163,  455,  465,
      466,  456,  530,  529,  445,  528,  527,  253,  445,  480,
      457,   60,   60,   60,   60,   68,   68,   68,   68,   99,
       99,  153,  153,  153,  153,  157,  157,  157,  157,  173,
      173,  173,  173,  176,  176,  176,  176,  248,  248,  248,

      248,  251,  251,  251,  251,  453,  526,  453,  453,  525,
      524,  523,  522,  521,  518,  517,  516,  515,  514,  513,
      512,  511,  510,  509,  508,  507,  506,  505,  504,  503,
      502,  501,  500,  499,  498,  497,  496,  495,  494,  493,
      492,  491,  488,  487,  486,  485,  484,  483,  482,  481,
      478,  477,  476,  475,  474,  473,  472,  471,  470,  469,
      468,  467,  463,  462,  461,  460,  459,  458,  452,  451,
      450,  449,  448,  447,  446,  442,  441,  440,  439,  438,
      437,  436,  435,  434,  433,  432,  431,  430,  429,  428,
      427,  426,  425,  424,  423,  422,  421,  420,  419,  418,

      417,  416,  415,  414,  413,  412,  411,  410,  409,  408,
      407,  406,  405,  404,  403,  402,  401,  400,  399,  398,
      397,  396,  395,  394,  393,  392,  391,  390,  389,  388,
      387,  386,  385,  384,  383,  382,  381,  380,  379,  378,
      377,  376,  375,  374,  373,  372,  371,  370,  369,  368,
      367,  366,  365,  364,  363,  362,  361,  360,  359,  358,
      354,  353,  352,  351,  350,  349,  348,  347,  346,  345,
      344,  343,  342,  341,  340,  339,  338,  337,  336,  335,
      334,  333,  332,  331,  330,  329,  328,  327,  326,  325,
      324,  323,  322,  321,  320,  319,  318,  317,  316,  313,

      312,  311,  310,  309,  308,  307,  306,  305,  304,  303,
      302,  301,  300,  299,  298,  297,  296,  295,  294,  293,
      292,  291,  290,  289,  288,  287,  286,  285,  284,  283,
      282,  281,  280,  279,  278,  277,  276,  275,  272,  271,
      270,  269,  268,  267,  264,  263,  262,  261,  260,  259,
      258,  255,  254,  240,  239,  238,  237,  234,  233,  230,
      225,  224,  219,  215,  212,  211,  210,  209,  208,  207,
      206,  203,  202,  201,  200,  199,  196,  195,  194,  193,
      188,  187,  184,  183,  182,  181,  180,  179,  172,  171,
      161,  160,  156,  150,  135,  127,  126,  123,  102,   96,

       71,   63,   59,  536,    3,  536,  536,  536,  536,  536,
      536,  536,  536,  536,  536,  536,  536,  536,  536,  536,
      536,  536,  536,  536,  536,  536,  536,  536,  536,  536,
      536,  536,  536,  536,  536,  536,  536,  536,  536,  536,
      536,  536,  536,  536,  536,  536,  536,  536,  536,  536,
      536,  536,  536,  536,  536,  536,  536,  536,  536,  536,
      536,  536,  536,  536,  536,  536,  536,  536,  536,  536,
      536,  536,  536
    } ;

static yyconst flex_int16_t yy_chk[774] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    5,    8,
        5,   10,   10,   11,   12,   16,   19,   23,   18,   25,
       19,   23,   19,   19,   19,   20,   16,   18,   18,   11,
       20,   27,   27,   25,   30,   25,   25,   20,   30,    8,

       12,   21,   34,   21,   21,   21,   37,   34,   22,   34,
       22,   22,   22,   21,   35,   37,   21,   21,   21,   35,
       22,  125,   35,   22,   22,   37,   36,   44,   21,  125,
       38,   44,   38,   36,   21,   22,   36,   41,   39,   36,
       44,   22,   38,   21,   41,   45,   21,   45,   39,   46,
       22,   39,   46,   55,   39,   48,   48,   50,   49,   51,
       52,   49,   50,   60,   51,   52,   48,  109,  109,   48,
       49,   58,   62,   58,   68,   62,   70,   49,  100,   88,
       87,  101,  141,   70,  542,   79,   79,   79,  112,  112,
      141,  534,  144,   60,   55,   79,   79,   88,   79,  137,

       68,  144,   83,   83,   83,   62,   87,  101,  100,   70,
       79,   79,   83,   83,  118,   83,   79,  137,  118,   84,
      113,   84,   84,   84,  133,  113,  142,   83,   83,  133,
      142,   84,  138,   83,   84,   84,  153,  135,   85,  135,
       85,   85,   85,  147,  154,  147,   84,  157,  138,  135,
       85,  158,   84,   85,   85,  155,  533,   86,  155,   86,
      159,   84,   86,   86,   86,   85,  153,  159,  164,  165,
      479,   85,  479,  157,  154,  173,  162,  158,  162,  248,
       85,  162,  162,  162,  166,  166,  166,  165,  155,  167,
      167,  167,  176,  159,  164,  170,  170,  178,  175,  182,

      167,  175,  167,  246,  178,  173,  190,  190,  197,  248,
      249,  197,  182,  170,  247,  167,  250,  251,  176,  250,
      167,  252,  170,  241,  241,  241,  242,  242,  242,  246,
      178,  175,  247,  303,  253,  529,  511,  242,  303,  242,
      249,  253,  303,  251,  427,  511,  427,  252,  443,  250,
      443,  528,  242,  454,  527,  445,  469,  242,  445,  454,
      454,  445,  525,  522,  427,  519,  518,  253,  443,  469,
      445,  537,  537,  537,  537,  538,  538,  538,  538,  539,
      539,  540,  540,  540,  540,  541,  541,  541,  541,  543,
      543,  543,  543,  544,  544,  544,  544,  545,  545,  545,

      545,  546,  546,  546,  546,  547,  517,  547,  547,  516,
      515,  514,  513,  512,  510,  509,  508,  507,  505,  503,
      502,  501,  500,  499,  498,  497,  496,  495,  494,  493,
      492,  491,  490,  489,  488,  487,  486,  485,  484,  483,
      482,  480,  478,  477,  476,  475,  474,  473,  471,  470,
      468,  467,  466,  465,  464,  462,  461,  460,  459,  457,
      456,  455,  453,  452,  451,  450,  447,  446,  441,  437,
      436,  434,  432,  430,  428,  425,  423,  422,  421,  419,
      418,  417,  416,  415,  413,  412,  410,  409,  407,  406,
      405,  403,  402,  401,  400,  399,  398,  396,  395,  392,

      388,  387,  385,  384,  383,  381,  380,  375,  374,  371,
      370,  369,  366,  365,  363,  362,  361,  360,  359,  357,
      356,  355,  353,  352,  351,  350,  349,  348,  346,  345,
      344,  343,  342,  341,  339,  338,  337,  336,  335,  334,
      331,  330,  329,  328,  327,  326,  325,  324,  323,  317,
      316,  313,  312,  311,  310,  309,  307,  306,  305,  304,
      301,  299,  298,  297,  296,  295,  294,  293,  292,  291,
      290,  289,  288,  287,  286,  285,  284,  283,  282,  280,
      278,  277,  276,  275,  274,  273,  270,  269,  268,  267,
      266,  265,  264,  263,  261,  259,  257,  256,  254,  240,

      239,  238,  237,  236,  235,  234,  233,  232,  231,  230,
      228,  227,  226,  225,  224,  223,  222,  221,  220,  219,
      218,  217,  216,  215,  214,  213,  212,  211,  210,  208,
      207,  206,  204,  203,  202,  200,  199,  198,  196,  195,
      194,  193,  192,  191,  189,  188,  187,  186,  185,  184,
      183,  181,  179,  156,  150,  149,  148,  146,  145,  143,
      140,  139,  136,  134,  132,  131,  130,  129,  128,  127,
      126,  123,  122,  121,  120,  119,  117,  116,  115,  114,
      111,  110,  108,  107,  106,  105,  104,  103,   98,   94,
       78,   76,   63,   53,   47,   43,   42,   40,   33,   26,

       15,    9,    7,    3,  536,  536,  536,  536,  536,  536,
      536,  536,  536,  536,  536,  536,  536,  536,  536,  536,
      536,  536,  536,  536,  536,  536,  536,  536,  536,  536,
      536,  536,  536,  536,  536,  536,  536,  536,  536,  536,
      536,  536,  536,  536,  536,  536,  536,  536,  536,  536,
      536,  536,  536,  536,  536,  536,  536,  536,  536,  536,
      536,  536,  536,  536,  536,  536,  536,  536,  536,  536,
      536,  536,  536
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "120lex.l"
/*
 *  John Goettsche
 *  CS445
 *  Homework #2
 *  revised lexer by Sandro Sigala.
 */
/*	$Id: lexer.l,v 1.2 1997/11/19 15:13:15 sandro Exp $	*/
/*
 * Copyright (c) 1997 Sandro Sigala <ssigala@globalnet.it>.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 * IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
 * NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
 * THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
/*
 * ISO C++ lexical analyzer.
 *
 * Based on the ISO C++ draft standard of December '96.
 */
#line 42 "120lex.l"
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <ctype.h>

#include "sdef.h"
#include "120gram.h"
#include "token.h"
#include "errors.h"

FileStack *topFile = NULL;
TypeStack *topType = NULL;
int lineno;
TreeNode *n;
FILE *yyin;
FILE *saved_yyin;
int exitStatus = 0;

static int yywrap(void);
void include();
void handle_include();
void pushTypeStack(int);
void popTypeStack();
void pushFileStack();
void popFileStack();
static void skip_until_eol(void);
static void skip_comment(void);
static int check_identifier(char *);
static int alac(Token *);
void lexerr(char *);

int using_namespace_std = 0;
int included_iostream = 0;
int included_cstdlib = 0;
int included_ctime = 0; 
int included_string = 0;
int included_fstream = 0;
int included_stdio = 0; 
int included_stdlib = 0;
int included_cmath = 0;
int typedefMode = 0;
int unionMode = 0;
#line 887 "<stdout>"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

int yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 93 "120lex.l"


#line 1077 "<stdout>"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 537 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 705 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 95 "120lex.l"
{ ++lineno; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 96 "120lex.l"
{ /* Ignore whitespace. */ }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 98 "120lex.l"
{ skip_comment(); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 99 "120lex.l"
{ skip_until_eol(); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 101 "120lex.l"
{ return '{'; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 102 "120lex.l"
{ return '{'; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 103 "120lex.l"
{ return '}'; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 104 "120lex.l"
{ return '}'; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 105 "120lex.l"
{ return '['; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 106 "120lex.l"
{ return '['; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 107 "120lex.l"
{ return ']'; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 108 "120lex.l"
{ return ']'; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 109 "120lex.l"
{ return '('; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 110 "120lex.l"
{ return ')'; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 111 "120lex.l"
{ return ';'; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 112 "120lex.l"
{ return ':'; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 113 "120lex.l"
{ return alac((Token *)createToken(ELLIPSIS)); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 114 "120lex.l"
{ return '?'; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 115 "120lex.l"
{ return alac((Token *)createToken(COLONCOLON)); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 116 "120lex.l"
{ return '.'; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 117 "120lex.l"
{ return alac((Token *)createToken(DOTSTAR)); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 118 "120lex.l"
{ return '+'; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 119 "120lex.l"
{ return '-'; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 120 "120lex.l"
{ return '*'; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 121 "120lex.l"
{ return '/'; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 122 "120lex.l"
{ return '%'; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 123 "120lex.l"
{ return '^'; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 124 "120lex.l"
{ return '^'; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 125 "120lex.l"
{ return '&'; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 126 "120lex.l"
{ return '&'; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 127 "120lex.l"
{ return '|'; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 128 "120lex.l"
{ return '|'; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 129 "120lex.l"
{ return '~'; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 130 "120lex.l"
{ return '~'; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 131 "120lex.l"
{ return '!'; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 132 "120lex.l"
{ return '!'; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 133 "120lex.l"
{ return '='; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 134 "120lex.l"
{ return '<'; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 135 "120lex.l"
{ return '>'; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 136 "120lex.l"
{ return alac((Token *)createToken(ADDEQ)); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 137 "120lex.l"
{ return alac((Token *)createToken(SUBEQ)); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 138 "120lex.l"
{ return alac((Token *)createToken(MULEQ)); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 139 "120lex.l"
{ return alac((Token *)createToken(DIVEQ)); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 140 "120lex.l"
{ return alac((Token *)createToken(MODEQ)); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 141 "120lex.l"
{ return alac((Token *)createToken(XOREQ)); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 142 "120lex.l"
{ return alac((Token *)createToken(XOREQ)); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 143 "120lex.l"
{ return alac((Token *)createToken(ANDEQ)); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 144 "120lex.l"
{ return alac((Token *)createToken(ANDEQ)); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 145 "120lex.l"
{ return alac((Token *)createToken(OREQ)); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 146 "120lex.l"
{ return alac((Token *)createToken(OREQ)); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 147 "120lex.l"
{ return alac((Token *)createToken(SL)); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 148 "120lex.l"
{ return alac((Token *)createToken(SR)); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 149 "120lex.l"
{ return alac((Token *)createToken(SLEQ)); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 150 "120lex.l"
{ return alac((Token *)createToken(SREQ)); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 151 "120lex.l"
{ return alac((Token *)createToken(EQ)); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 152 "120lex.l"
{ return alac((Token *)createToken(NOTEQ)); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 153 "120lex.l"
{ return alac((Token *)createToken(NOTEQ)); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 154 "120lex.l"
{ return alac((Token *)createToken(LTEQ)); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 155 "120lex.l"
{ return alac((Token *)createToken(GTEQ)); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 156 "120lex.l"
{ return alac((Token *)createToken(ANDAND)); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 157 "120lex.l"
{ return alac((Token *)createToken(ANDAND)); }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 158 "120lex.l"
{ return alac((Token *)createToken(OROR)); }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 159 "120lex.l"
{ return alac((Token *)createToken(OROR)); }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 160 "120lex.l"
{ return alac((Token *)createToken(PLUSPLUS)); }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 161 "120lex.l"
{ return alac((Token *)createToken(MINUSMINUS)); }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 162 "120lex.l"
{ return ','; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 163 "120lex.l"
{ return alac((Token *)createToken(ARROWSTAR)); }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 164 "120lex.l"
{ return alac((Token *)createToken(ARROW)); }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 165 "120lex.l"
{ using_namespace_std = 1; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 166 "120lex.l"
{ return alac((Token *)createToken(ASM)); }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 167 "120lex.l"
{ return alac((Token *)createToken(AUTO)); }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 168 "120lex.l"
{ return alac((Token *)createToken(BOOL)); }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 169 "120lex.l"
{ return alac((Token *)createToken(BREAK)); }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 170 "120lex.l"
{ return alac((Token *)createToken(CASE)); }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 171 "120lex.l"
{ return alac((Token *)createToken(CATCH)); }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 172 "120lex.l"
{ return alac((Token *)createToken(CHAR)); }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 173 "120lex.l"
{ pushTypeStack(CLASS);
													return alac((Token *)createToken(CLASS)); }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 175 "120lex.l"
{ return alac((Token *)createToken(CONST)); }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 176 "120lex.l"
{ return alac((Token *)createToken(CONST_CAST)); }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 177 "120lex.l"
{ return alac((Token *)createToken(CONTINUE)); }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 178 "120lex.l"
{ return alac((Token *)createToken(DEFAULT)); }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 179 "120lex.l"
{ return alac((Token *)createToken(DELETE)); }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 180 "120lex.l"
{ return alac((Token *)createToken(DO)); }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 181 "120lex.l"
{ return alac((Token *)createToken(DOUBLE)); }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 182 "120lex.l"
{ return alac((Token *)createToken(DYNAMIC_CAST)); }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 183 "120lex.l"
{ return alac((Token *)createToken(ELSE)); }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 184 "120lex.l"
{ pushTypeStack(ENUM);
													return alac((Token *)createToken(ENUM)); }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 186 "120lex.l"
{ return alac((Token *)createToken(EXPLICIT)); }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 187 "120lex.l"
{ return alac((Token *)createToken(EXPORT)); }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 188 "120lex.l"
{ return alac((Token *)createToken(EXTERN)); }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 189 "120lex.l"
{ return alac((Token *)createToken(FALSE)); }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 190 "120lex.l"
{ return alac((Token *)createToken(FLOAT)); }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 191 "120lex.l"
{ return alac((Token *)createToken(FOR)); }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 192 "120lex.l"
{ return alac((Token *)createToken(FRIEND)); }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 193 "120lex.l"
{ return alac((Token *)createToken(GOTO)); }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 194 "120lex.l"
{ return alac((Token *)createToken(IF)); }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 195 "120lex.l"
{ return alac((Token *)createToken(INLINE)); }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 196 "120lex.l"
{ return alac((Token *)createToken(INT)); }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 197 "120lex.l"
{ return alac((Token *)createToken(LONG)); }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 198 "120lex.l"
{ return alac((Token *)createToken(MUTABLE)); }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 199 "120lex.l"
{ pushTypeStack(NAMESPACE);
													return alac((Token *)createToken(NAMESPACE)); }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 201 "120lex.l"
{ return alac((Token *)createToken(NEW)); }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 202 "120lex.l"
{ return alac((Token *)createToken(OPERATOR)); }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 203 "120lex.l"
{ return alac((Token *)createToken(PRIVATE)); }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 204 "120lex.l"
{ return alac((Token *)createToken(PROTECTED)); }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 205 "120lex.l"
{ return alac((Token *)createToken(PUBLIC)); }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 206 "120lex.l"
{ return alac((Token *)createToken(REGISTER)); }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 207 "120lex.l"
{ return alac((Token *)createToken(REINTERPRET_CAST)); }
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 208 "120lex.l"
{ return alac((Token *)createToken(RETURN)); }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 209 "120lex.l"
{ return alac((Token *)createToken(SHORT)); }
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 210 "120lex.l"
{ return alac((Token *)createToken(SIGNED)); }
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 211 "120lex.l"
{ return alac((Token *)createToken(SIZEOF)); }
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 212 "120lex.l"
{ return alac((Token *)createToken(STATIC)); }
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 213 "120lex.l"
{ return alac((Token *)createToken(STATIC_CAST)); }
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 214 "120lex.l"
{ pushTypeStack(STRUCT);
													return alac((Token *)createToken(STRUCT)); }
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 216 "120lex.l"
{ return alac((Token *)createToken(SWITCH)); }
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 217 "120lex.l"
{ exitStatus = 3;
													getErrorMessage(ER_NOT_SUPPORTED);
													lexerr(yytext);
													/*pushTypeStack(TEMPLATE);
													return alac((Token *)createToken(TEMPLATE));*/ }
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 222 "120lex.l"
{ return alac((Token *)createToken(THIS)); }
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 223 "120lex.l"
{ return alac((Token *)createToken(THROW)); }
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 224 "120lex.l"
{ return alac((Token *)createToken(TRUE)); }
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 225 "120lex.l"
{ return alac((Token *)createToken(TRY)); }
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 226 "120lex.l"
{ typedefMode = 1;
													return alac((Token *)createToken(TYPEDEF)); }
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 228 "120lex.l"
{ return alac((Token *)createToken(TYPEID)); }
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 229 "120lex.l"
{ return alac((Token *)createToken(TYPENAME)); }
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 230 "120lex.l"
{ unionMode = 1;
													return alac((Token *)createToken(UNION)); }
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 232 "120lex.l"
{ return alac((Token *)createToken(UNSIGNED)); }
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 233 "120lex.l"
{ return alac((Token *)createToken(USING)); }
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 234 "120lex.l"
{ return alac((Token *)createToken(VIRTUAL)); }
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 235 "120lex.l"
{ return alac((Token *)createToken(VOID)); }
	YY_BREAK
case 130:
YY_RULE_SETUP
#line 236 "120lex.l"
{ return alac((Token *)createToken(VOLATILE)); }
	YY_BREAK
case 131:
YY_RULE_SETUP
#line 237 "120lex.l"
{ return alac((Token *)createToken(WCHAR_T)); }
	YY_BREAK
case 132:
YY_RULE_SETUP
#line 238 "120lex.l"
{ return alac((Token *)createToken(WHILE)); }
	YY_BREAK
case 133:
/* rule 133 can match eol */
YY_RULE_SETUP
#line 240 "120lex.l"
{ handle_include(); }
	YY_BREAK
case 134:
YY_RULE_SETUP
#line 242 "120lex.l"
{ include();
													included_iostream = 1; }
	YY_BREAK
case 135:
YY_RULE_SETUP
#line 244 "120lex.l"
{ include();
													included_cstdlib = 1; }
	YY_BREAK
case 136:
YY_RULE_SETUP
#line 246 "120lex.l"
{ include();
													included_ctime = 1; }
	YY_BREAK
case 137:
YY_RULE_SETUP
#line 248 "120lex.l"
{ include();
													included_string = 1; }
	YY_BREAK
case 138:
YY_RULE_SETUP
#line 250 "120lex.l"
{ include();
													included_string = 1; }
	YY_BREAK
case 139:
YY_RULE_SETUP
#line 252 "120lex.l"
{ include();
													included_fstream = 1; }
	YY_BREAK
case 140:
YY_RULE_SETUP
#line 254 "120lex.l"
{ include();
													included_stdio = 1; }
	YY_BREAK
case 141:
YY_RULE_SETUP
#line 256 "120lex.l"
{ include();
													included_stdlib = 1; }
	YY_BREAK
case 142:
YY_RULE_SETUP
#line 258 "120lex.l"
{ include();
													included_cmath = 1; }
	YY_BREAK
case 143:
YY_RULE_SETUP
#line 261 "120lex.l"
{ return alac((Token *)createToken(check_identifier(yytext))); }
	YY_BREAK
case 144:
YY_RULE_SETUP
#line 263 "120lex.l"
{ return alac((Token *)createToken(INTEGER)); }
	YY_BREAK
case 145:
YY_RULE_SETUP
#line 264 "120lex.l"
{ return alac((Token *)createToken(INTEGER)); }
	YY_BREAK
case 146:
YY_RULE_SETUP
#line 265 "120lex.l"
{ return alac((Token *)createToken(INTEGER)); }
	YY_BREAK
case 147:
YY_RULE_SETUP
#line 267 "120lex.l"
{ return alac((Token *)createToken(FLOATING)); }
	YY_BREAK
case 148:
YY_RULE_SETUP
#line 268 "120lex.l"
{ return alac((Token *)createToken(FLOATING)); }
	YY_BREAK
case 149:
/* rule 149 can match eol */
YY_RULE_SETUP
#line 270 "120lex.l"
{ return alac((Token *)createToken(CHARACTER)); }
	YY_BREAK
case 150:
/* rule 150 can match eol */
YY_RULE_SETUP
#line 271 "120lex.l"
{ return alac((Token *)createToken(CHARACTER)); }
	YY_BREAK
case 151:
/* rule 151 can match eol */
YY_RULE_SETUP
#line 272 "120lex.l"
{ exitStatus =1;
													getErrorMessage(ER_MALF_CHAR); 
													lexerr(NULL); }
	YY_BREAK
case 152:
/* rule 152 can match eol */
YY_RULE_SETUP
#line 275 "120lex.l"
{ exitStatus =1;
													getErrorMessage(ER_MALF_CHAR); 
													lexerr(NULL); }
	YY_BREAK
case 153:
/* rule 153 can match eol */
YY_RULE_SETUP
#line 278 "120lex.l"
{ return alac((Token *)createToken(STRING)); }
	YY_BREAK
case 154:
/* rule 154 can match eol */
YY_RULE_SETUP
#line 279 "120lex.l"
{ return alac((Token *)createToken(STRING)); }
	YY_BREAK
case 155:
/* rule 155 can match eol */
YY_RULE_SETUP
#line 280 "120lex.l"
{ exitStatus =1;
													getErrorMessage(ER_STRING_CLOSE);
													lexerr(NULL); }
	YY_BREAK
case 156:
/* rule 156 can match eol */
YY_RULE_SETUP
#line 283 "120lex.l"
{ exitStatus =1;
													getErrorMessage(ER_STRING_CLOSE);
													lexerr(NULL); }
	YY_BREAK
case 157:
YY_RULE_SETUP
#line 287 "120lex.l"
{ exitStatus =1;
													getErrorMessage(ER_UNREC_TOKEN);
													lexerr(NULL); }
	YY_BREAK
case YY_STATE_EOF(INITIAL):
#line 291 "120lex.l"
{ popFileStack();
													yypop_buffer_state();
													if ( !YY_CURRENT_BUFFER ) {
														yyterminate();
													}
												}
	YY_BREAK
case 158:
YY_RULE_SETUP
#line 297 "120lex.l"
ECHO;
	YY_BREAK
#line 1998 "<stdout>"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 537 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 537 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 536);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 297 "120lex.l"



static int
yywrap(void)
{
	return 1;
}

Token *createToken(int tcode){
	Token *token = (Token *)calloc(1, sizeof(Token));
	if(token == NULL)memoryError();
	
	int length = strlen(yytext) + 1;
	char *text = (char *)calloc(length, sizeof(char));
	if(text == NULL) memoryError();
   strcpy(text, yytext); 
	token->category = tcode;
   token->text = text;
   token->lineno = lineno;
	
	char *filename = (char *)calloc(strlen(fname) + 1, sizeof(char));
	if(filename == NULL) memoryError();
	strcpy(filename, fname);
   token->filename =filename;
	
	if(tcode == INTEGER){ 
		token->ival = atoi(token->text);
		//printf("*** %d ***\n", token->ival);
	}
   if(tcode == STRING){
      token->ival = length;
      int *st = (int *)calloc(length, sizeof(int));
		if(st == NULL) memoryError();
      int i;
      for(i = 0; i < length; i++) st[i] = (int)text[i];
      token->sval = st;
   }
	if(tcode == TRUE) token->ival = 1;
	if(tcode == FALSE) token->ival = 0;
	else token->sval = NULL;
	
	return token;
}

void pushTypeStack(int tcode){
	TypeStack *typeStack = (TypeStack *)calloc(1, sizeof(TypeStack));
	if(typeStack == NULL) memoryError();
	typeStack->tcode = tcode;
	if(topType == NULL){
		topType = typeStack;
		topType->next = NULL;
	} else {
		typeStack->next = topType;
		topType = typeStack;
	}
}

void popTypeStack(){
	if(topType != NULL){
		topType = topType->next;
	}
}

void pushFileStack(){
	FileStack *fileStack = (FileStack *)calloc(1, sizeof(FileStack));
	if(fileStack == NULL) memoryError();
	char *filename = (char *)calloc(strlen(fname) + 1, sizeof(char));
	if(filename == NULL) memoryError();
	strcpy(filename, fname);
	fileStack->filename = filename;
	fileStack->lineno = lineno;
	if (topFile == NULL){
		topFile = fileStack;
		topFile->next = NULL;
	} else {
		fileStack->next = topFile;
		topFile = fileStack;
	}
}

void popFileStack(){
	if(topFile!=NULL){
		fname = topFile->filename;
		lineno = topFile->lineno;
		topFile=topFile->next;
	}
}

void handle_include()
{
	pushFileStack();
   lineno = 1;
   saved_yyin = yyin;
	
   fname = strchr(yytext, '\"')+1;
   fname[strlen(fname)-1] = '\0';
   yyin = fopen(fname,"r");
   if (yyin == NULL) {
		getErrorMessage(ER_FILE_NOT_FOUND);
		yyerror(fname);
		exit(1);
   }
	yypush_buffer_state(yy_create_buffer(yyin,YY_BUF_SIZE));
}

void include()
{
	pushFileStack();
	lineno = 1;
	saved_yyin = yyin;
	
	fname = strchr(yytext, '<')+1;
	fname[strlen(fname)-1] = '\0';
	fname = strcat(fname, ".a");
	yyin = fopen(fname,"r");
	if (yyin == NULL) {
		getErrorMessage(ER_FILE_NOT_FOUND);
		yyerror(fname);
		exit(1);
   }
	yypush_buffer_state(yy_create_buffer(yyin,YY_BUF_SIZE));
}

/*
 * We use this routine instead a lex pattern because we don't need
 * to save the matched comment in the `yytext' buffer.
 */
static void
skip_comment(void)
{
	int c1, c2;

	c1 = input();
	c2 = input();

	while (c2 != EOF && !(c1 == '*' && c2 == '/')) {
		if (c1 == '\n')
			++lineno;
		c1 = c2;
		c2 = input();
	}
}

/*
 * See the previous comment for an explanation.
 */
static void
skip_until_eol(void)
{
	int c;

	while ((c = input()) != EOF && c != '\n')
		;
	++lineno;
}

/*
 * Type name table.
 * Replace this with a hash table, when you get a chance.
 */
struct typenametable_entry {
   char *name;
   int category;
   struct typenametable_entry *next;
   } *head;

int typenametable_lookup(char *s)
{
   struct typenametable_entry *tmp = head;
   while (tmp) {
      if (!strcmp(s, tmp->name)) return tmp->category;
      tmp = tmp->next;
   }	
	
	if(strcmp(s, "string") == 0){
		typenametable_insert(s, STR_TYPE);
		return STR_TYPE;
	}
	
	if(topType!=NULL){
		switch(topType->tcode){
			case CLASS : 
				popTypeStack();
				typenametable_insert(s, CLASS_NAME);
				return CLASS_NAME;
		/*	case TYPEDEF : 
				popTypeStack();
				typenametable_insert(s, TYPEDEF_NAME);
				return TYPEDEF_NAME;*/
			case ENUM : 
				popTypeStack();
				typenametable_insert(s, ENUM_NAME);
				return ENUM_NAME;
			case NAMESPACE : 
				popTypeStack();
				typenametable_insert(s, NAMESPACE_NAME);
				return NAMESPACE_NAME;
		/*	case TEMPLATE : 
				popTypeStack();
				typenametable_insert(s, TEMPLATE_NAME);
				return TEMPLATE_NAME;*/
			case STRUCT : 
				popTypeStack();
				typenametable_insert(s, CLASS_NAME);
				return CLASS_NAME;
		/*	case UNION : 
				popTypeStack();
				typenametable_insert(s, CLASS_NAME);
				return CLASS_NAME;*/
		}
	}
   return IDENTIFIER;
}

int typenametable_insert(char *s, int cat)
{
   struct typenametable_entry *tmp = head;
   while (tmp) {
      if (!strcmp(s, tmp->name)) {
         fprintf(stderr,
	    "warning, %s is already in the typename table as a %d\n",
	    s, tmp->category );
         return tmp->category;
         }
      tmp = tmp->next;
   }
   tmp = calloc(1, sizeof (struct typenametable_entry));
   if(!tmp) { memoryError();/*fprintf(stderr, "tnti out of memory\n"); return -1;*/ }
   tmp->name = strdup(s);
   tmp->category = cat;
   tmp->next = head;
   head = tmp;
}

static int
check_identifier(char *s)
{
	return typenametable_lookup(s);
}

static int alac(Token *token)
{
	int i;
	if((yylval.n = (TreeNode *)calloc(1, sizeof(TreeNode))) == NULL) memoryError(); 
	yylval.n->symbol = token->category;
	yylval.n->u.t.token = token;
	return token->category;
}


